

#shinyserver start point----
 shinyServer(function(input, output,session) {
   
   books <- getBooks()
   print(books)
   dtedit2(input, output,
           name = 'tcp_prior1',
           thedata = books,
           edit.cols = c('fname'),
           edit.label.cols = c('名称'),
           input.types = c(fname='textAreaInput'),
           input.choices = list(fname = unique(unlist(books$fname))),
           view.cols = c('fid','fname'),
           view.captions = c('序号','名称'),
           show.insert = F,
           show.copy = F,
           show.delete = F,
           title.edit = '加急处理',
           label.edit = '加急处理',
           callback.update = books.update.callback,
           callback.insert = books.insert.callback,
           callback.delete = books.delete.callback)
   dtedit2(input, output,
           name = 'tcp_prior2',
           thedata = books,
           edit.cols = c('fname'),
           edit.label.cols = c('名称'),
           input.types = c(fname='textAreaInput'),
           input.choices = list(fname = unique(unlist(books$fname))),
           view.cols = c('fid','fname'),
           view.captions = c('序号','名称'),
           show.insert = F,
           show.copy = F,
           show.delete = F,
           title.edit = '普通处理',
           label.edit = '普通处理',
           callback.update = books.update.callback,
           callback.insert = books.insert.callback,
           callback.delete = books.delete.callback)
   dtedit2(input, output,
           name = 'tcp_prior3',
           thedata = books,
           edit.cols = c('fname'),
           edit.label.cols = c('名称'),
           input.types = c(fname='textAreaInput'),
           input.choices = list(fname = unique(unlist(books$fname))),
           view.cols = c('fid','fname'),
           view.captions = c('序号','名称'),
           show.insert = F,
           show.copy = F,
           show.delete = F,
           show.update=F,
           callback.update = books.update.callback,
           callback.insert = books.insert.callback,
           callback.delete = books.delete.callback)
   dtedit2(input, output,
           name = 'tcp_prior4',
           thedata = books,
           edit.cols = c('fname'),
           edit.label.cols = c('名称'),
           input.types = c(fname='textAreaInput'),
           input.choices = list(fname = unique(unlist(books$fname))),
           view.cols = c('fid','fname'),
           view.captions = c('序号','名称'),
           show.insert = F,
           show.copy = F,
           show.delete = F,
           show.update=F,
           callback.update = books.update.callback,
           callback.insert = books.insert.callback,
           callback.delete = books.delete.callback)
   
  
})
